services:
  portfolio:
    build: .
    image: portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    networks:
      - public-ingress
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`pbartoszewski.pl`) || Host(`www.pbartoszewski.pl`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls=true"
      - "traefik.http.routers.portfolio.tls.certresolver=letsencrypt"
      - "traefik.http.services.portfolio.loadbalancer.server.port=80"
      - "traefik.docker.network=public_net"

networks:
  public-ingress:
    name: public_net
    external: true